### ISSUE TITLE
Feed in a CSV and get back additional Geographic Information

### ISSUE THREAD

**Issue by EricRoche** [codeforkansascity/address-api#108]
Hello,

I would like to upload a csv with partial address information. For example, one data point might be:
`6306 E 102nd St`
`7109 E 112th St`
`8709 E 114th Ter`

Address API would then return the following (plus the original street address) as separate columns in a table/csv.
1. City
2. State
3. Zip
4. Council District
5. Neighborhood

**Comment by zmon** [comment]
Moved to new version codeforkansascity/addressapi-api#7
