### ISSUE TITLE
Jackson County MO Data Request

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/address-api#16]
This will be a point of discussion on Monday August 3rds meeting

We have been in contact with Jackson County and they are willing to entertain our request for ongoing data.
They suggested that the next step is to confirm and present our request to them.

The following is the list from their email:
- Time Periods we would like
- Our data needs
  - Liens / Encumbrances,
  - TIF / Exemption & Abatements,
  - Address,
  - KIVA Pin,
  - County APN,
  - Owner & Address,
  - Assessed Land / Improvement,
  - Square Feet,
  - Year Built,
  - Living Area,
  - Tax Code,
  - Property Code,
  - Land Use Type,
  - Market Value,
  - Taxable Value,
  - Tax Status,
  - Legal Description and Subdivision (including lot and block).

The following we can get from other sources
- zoning (available through KCMO?, especially if seeking data from north of river),
- census data

For comparison look at the data that Jim DeLise collected and what is in the County's column

**Comment by amandaCCF** [comment]
@zmon Will Tax Status have information tax delinquency info?

**Comment by zmon** [comment]
@amandaCCF I will put that in the request as a separate item.

**Comment by JRDeLisle** [comment]
Did we get a list of property descriptive data used by Jackson County in their assessment model? This would include building height (number of floors), number of rooms, baths, garage/parking, etc. along with some condition. If we knew what's available, we could modify our request. However, that may be for a future extension.

**Comment by zmon** [comment]
@eroche5 said: May want to also have the county throw in the zip code, and City. Unless you are limiting your request to just KCMO proper.
