### ISSUE TITLE
Normalize a passed in address

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/address-api#25]
I have the need to retrieve a normalized address from an address that is passed into the address api.

Here is the following example of a query

``` JSON
    GET /address?address=1115%20Main%20Street
```

``` JSON
     {
         "street": "1115 Main St.",
         "state": "MO",
         "city": "Kansas City",
         "neighborhood": "QH"
     }
```

**Comment by zmon** [comment]
@JakeLaCombe we have implemented the endpoint http://dev-api.codeforkc.org//address-attributes/V0/210%20W%2019TH%20TER?city=Kansas%20City&state=mo which gives you more than just the address.
