### ISSUE TITLE
Better Split up the address into further attribute.

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/address-api#97]
I was looking through the address api by neighborhood, and noticed the following return structure for the address

```
"address_id":95420,
"single_line_address":"11 E 31ST ST, KANSAS CITY, MO",
"city":"KANSAS CITY",
"state":"MO",
"zip":"64108"
```

I am looking to integrate this with the following dataset. http://webfusion.kcmo.org/coldfusionapps/neighborhood/rentalreg/PropList.cfm. To combine these datasets, I do a split on the single_line_address on the comma, and take the first value, which corresponds to the street of the address. This doesn't feel like a solid approach for integrating with this dataset. The street is fine, but I'd like to access it without having to do complex string logic.
## What am I looking for?

I propose we add an attribute to each address called street, which contains the street address of the given address. It would make the data structure look like this.

```
"address_id":95420,
"single_line_address":"11 E 31ST ST, KANSAS CITY, MO",
"street":"11 E 31ST ST"
"city":"KANSAS CITY",
"state":"MO",
"zip":"64108"
```

**Comment by zmon** [comment]
Notes:

Field name will be "street_address" or "address" which the city uses in their vacantparcels layer and does not have city and state.

Potential things to change:
- N/A data/jackson_county_mo/tax_neighborhoods/load.php - Only used to find a record
- N/A data/KCMO-all-addresses/02-add-address-api.php - Only used to find a record
- N/A data/KCMO-all-addresses/AddressStandardizationSolution.php
- N/A src/Code4KC/Address/Address.php - Query only
- N/A src/Code4KC/Address/AddressAlias.php - Query only function find_by_single_line_address($single_line_address)
- N/A src/Code4KC/Address/Census.php - Read only
- N/A src/Code4KC/Address/LandUseCodes.php - Read only
- N/A tests/integration/Code4KC/Address/TypeAheadTest.php - Read only
- N/A webroot/index.php - Read only, builds a single_line_address from AddressStandardizationSolution
- N/A vendor/Convissor/address/AddressStandardizationSolution.php
- [ ] data/KCMO-all-addresses/03-add-new-addresses.php - Add street_address
- [ ] data/parcel-viewer_062015_addresses/load.php - Looks like it adds address records
- [ ] src/Code4KC/Address/AddressTable.php - Updates
- [ ] src/Code4KC/Address/BaseTable.php - single_line_address is dead code
- [ ]  webroot/api-docs/swagger.json
- [ ] api-docs/swagger.json

Update google spread sheet https://docs.google.com/spreadsheets/d/1RPVez3dgZWaPNFRb0ShVmrvo9zXKBnYtyQxoH4vxzc8/edit#gid=0

**Comment by zmon** [comment]
Added `street_address` same as single line address but without city and state.  @JakeLaCombe
